### ISSUE TITLE
Can't access the azure raw image in link from the docs

### ISSUE THREAD

**Issue by DanielMabbett** [openflighthpc/openflighthpc-images#1]
Hey guys, 

I was looking at the docs and noticed that I get an "access denied" from your s3 bucket: 

Page: https://images.openflighthpc.org/en/latest/cloud/controller.html
Broken Link: https://flight-images.s3.eu-west-2.amazonaws.com/cloudcontroller-0310191057_azure.raw

Issue: Access Denied

Can we make the object public, please?

Many thanks.

**Comment by WilliamMcCumstie** [comment]
I am getting a similar error when trying to download the `flight-runway` repo:
```
wget https://openflighthpc.s3-eu-west-1.amazonaws.com/repos/openflight/openflight.repo
--2020-01-13 11:16:39--  https://openflighthpc.s3-eu-west-1.amazonaws.com/repos/openflight/openflight.repo
Resolving openflighthpc.s3-eu-west-1.amazonaws.com (openflighthpc.s3-eu-west-1.amazonaws.com)... 52.218.24.224
Connecting to openflighthpc.s3-eu-west-1.amazonaws.com (openflighthpc.s3-eu-west-1.amazonaws.com)|52.218.24.224|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-01-13 11:16:39 ERROR 403: Forbidden.
```

**Comment by ColonelPanics** [comment]
Apologies @DanielMabbett & @WilliamMcCumstie, over the Xmas break I was doing account and storage migration. Looks like there are a couple of dead links and outdated docs that need to be tidied up.

Daniel - That link is active again and you should be able to download the cloud controller image.

William - The repositories have migrated so the 2 methods of setting up the OpenFlight repos are either:
- Installing the openflight-release RPM (`yum install https://repo.openflighthpc.org/openflight/centos/7/x86_64/openflighthpc-release-2-1.noarch.rpm`)
- Downloading the individual repo files (the production repo being at `https://repo.openflighthpc.org/openflight/centos/7/openflight.repo`)

**Comment by DanielMabbett** [comment]
Brill thanks for the quick response.
